---
- hosts: all
  gather_facts: false
  become: true
  force_handlers: true

  pre_tasks:
        
    - name: Gather system information
      ansible.builtin.setup:
      
    - name: Display system information
      ansible.builtin.debug:
        msg: 
          - "Beginning Satellite installation on {{ inventory_hostname }}"
          - "Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Architecture: {{ ansible_architecture }}"

  roles:
    - role: rhel_satellite_deploy
      vars:
        # To customize variables see the default/main.yml section
        # sat_pass:    "" # Default admin password
        # sat_actkey:  "" # Activation key from console.redhat.com     
      tags: satellite_installation

  post_tasks:    

    - name: Display final status
      ansible.builtin.debug:
        msg:
          - "Red Hat Satellite installation completed successfully"
          - "Organization: {{ sat_org }}"
          - "Server accessible at: https://{{ ansible_fqdn }}"
          - "User: admin"
          - "Password: {{ sat_pass }}"
          