---
- name: Unregister the system
  community.general.redhat_subscription:
    state: absent
  tags: unregister

- name: Deploy rhsm.conf configuration
  ansible.builtin.template:
    src: rhsm.conf.j2
    dest: /etc/rhsm/rhsm.conf
    backup: yes
    owner: root
    group: root
    mode: '0644'
  tags: deployrhsm

- name: Register system with Red Hat
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ sat_actkey }}"
    org_id: "{{ sat_rhsm_org_id }}"
    force_register: true    
  register: registration_result
  no_log: true
  tags: register

- name: Disable all repositories
  community.general.rhsm_repository:
    name: '*'
    state: disabled
  tags: disablerepo

- name: Enable Satellite repositories
  community.general.rhsm_repository:
    name: "{{ sat_os_version + sat_bin_version }}"
    state: enabled
  tags: enablerepo

- name: Install Satellite package
  ansible.builtin.dnf:
    name: satellite
    state: present
  tags: installsat

- name: force all notified handlers to run at this point
  meta: flush_handlers